dwmorrin/gas-eco

- js/Logic.html
> fix: clears omnibox for valid double scans

- css/Style.html
- js/Display.html
Adds css rule for "non-serialized" item rows
Updates displaying logic for items to add class for
non-serialized items to item rows.
fixes issue #25
> fix: indicates changeable quantity in item row

- js/app/Refresh.html
sorts open forms and gets new index in app.refresh
fixes issue #28
> fix: new form indexing

- js/Display.html
- js/Logic.html
- js/app/DoCommand.html
- js/app/Handlers.html
* deletes js/Display::displayNewForm
* moves displayNewForm code to js/app/DoCommand case handler for
displayNewForm
* adds helper function js/Logic::isBlankForm
* adds isBlankForm check to js/app/Handlers
fixes issue #50
> fix: pops blank forms off stack

- js/app/DoCommand.html
* only applies when lowering quantity on items previously saved
fixes issue #41
> feat: error message when lowering quantity

- css/Style.html
- gs/Item.js
- gs/Main.js
- gs/Student.js
- html/Archive.html
- js/Display.html
- js/Init.html
- js/Logic.html
- js/Utility.html
- js/app/DoCommand.html
- js/app/Handlers.html
- js/app/Modal.html
- js/app/Omnibox.html
- js/app/pages/Archive.html
- js/app/pages/Form.html
feat: Implement system of flags - Incomplete Checkouts
allows forms to be closed when items are not returned or students don't
checkout by clicking the item or student and marking the item  as "not found"
or the student as "left without checking out". These put a red warning
in the item's checkIn or student's checkOut column and these cases can
be filtered in the archive.
fixes issue #43
> feat: Implement system of flags - Incomplete Checkouts

- js/app/DoCommand.html
- js/app/pages/Archive.html
* removes closed form (archive) page initialization from doCommand
* adds initialization to pages/Archive .show function
> fix: refactor closed form init into .show function

- css/Style.html
- js/Display.html
- js/app/pages/Form.html
* adds toast() function which displays a message to user
* adds toast class to stylesheet with animations
* app.pages.form will toast() student and item changes
fixes issue #64
> feat: toast successful changes to form

- js/app/Omnibox.html
> fix: clears omnibox upon double item check-out

- js/Display.html
* also fills entire row with the message
fixes issue #86
> fix: removes mention of archive

- js/app/DoCommand.html
- js/app/Omnibox.html
- js/app/main.html
> fix: replace "10000" with string constant

- js/Display.html
- js/app/DoCommand.html
- js/app/pages/Form.html
* on display the "other" option is reset
* on click (to edit), select resets to default
fixes issue #13 
alternative to PR #77
> fix: resets location select

- gs/Main.js
- gs/Sheets.js
- js/app/DoCommand.html
- js/app/Modal.html
- js/app/Refresh.html
* saves rejected forms to the Forms spreadsheet
* offers user the choice of viewing old form or replacing it
fixes issue #2
> feat: adds basic collision handling

- css/Style.html
- html/index.html
* separating css sheet allows for better syntax highlighting and linting
> fix: moves external stylesheet to index.html

- js/Display.html
- js/Utility.html
- js/app/DoCommand.html
- js/app/Refresh.html
- js/app/pages/Archive.html
* forms remain sorted across context changes for both open and closed form stacks
fixes issue #44
> fix: forms remain sorted

- js/Logic.html
* adds check for undefined object that threw unhandled error
* adds formatting changes
> fix: adds guard to prevent unhandled error

- js/Utility.html
- js/app/pages/Archive.html
- js/app/pages/OpenForms.html
* clicking on columns will toggle ascending/descending sort
see issue #100
> feat: sort descending

- js/app/Refresh.html
* updates `app.refresh` to use `utility.sortForm`
* bug fixed: `app.refresh` case `checkForms` updates `currentIndex`
> fix: background form check updates `currentIndex`

- js/app/DoCommand.html
- js/app/pages/Form.html
> fix: determines correct key for looking up item

- js/Init.html
- js/app/DoCommand.html
- js/app/Handlers.html
- js/app/Modal.html
- js/app/Refresh.html
- js/app/pages/Form.html
> feat: locks clicks and keydowns during update

- html/Archive.html
- html/index.html
- js/Utility.html
- js/app/main.html
- js/app/pages/Archive.html
- js/app/pages/ArchiveQuery.html
`app.pages.archive.query` was a small experiment/demo that was never meant to expand the way it did.
This is a step towards a more manageable system.
> fix: query

- js/app/Modal.html
> fix: updates message to user for signature capture

- css/Style.html
* adds css rule `position: relative` to `<header>` to keep username
positioning relative
> fix: lines up username display with form sections

- html/Form.html
- js/Display.html
- js/Utility.html
- js/app/DoCommand.html
- js/app/Handlers.html
- js/app/Omnibox.html
- js/app/pages/Form.html
Allow the user to copy a list of items from one form into their clipboard and paste it into the omnibox of another form
prevents the user from tampering with the copied information by pulling
all important data from the cache and overwriting it with known correct
values
rejects any pasted item that is not a manual item and not in the cache
fixes issue #104
> feat: copy a list of items

- js/app/pages/Form.html
* sets timeout after every change that satisfies form.isReadyToPost
* timeout set for 60 seconds
fixes issue #135
> feat: autosave form

- js/app/Omnibox.html
* per beta tester feedback, this is the perferred behavior
fixes issue #137
> fix: clears omnibox of invalid entries

- css/Style.html
- html/Modal.html
- js/Display.html
- js/Init.html
- js/app/DoCommand.html
- js/app/Handlers.html
- js/app/Modal.html
- js/app/Omnibox.html
- js/app/pages/Form.html
* also major rework of the event handler dispatch system!
* adds two buttons for non-serialized items: one user supplied value,
one "plus one" value
see issue #141
> feat: quantity change buttons for items

- gs/Errors.js
- gs/Form.js
- gs/Main.js
- gs/Sheets.js
- gs/Student.js
- js/app/DoCommand.html
- js/app/Refresh.html
- js/app/pages/Form.html
* adds several error types in a Errors.js file
* ErrorFormCollision
* ErrorFormDataInvalid
* ErrorFormInvalid
* Bad data in the open forms is automatically skipped and deleted
> feat: new Error types, form validation

- css/Style.html
- js/Display.html
> feat: highlights column sorted by

- js/Display.html
- js/Inventory.html
- js/Item.html
- js/Utility.html
- js/app/DoCommand.html
- js/app/Handlers.html
- js/app/Modal.html
- js/app/Omnibox.html
* adds text hints to user for checking in/out students and items
* refactors item display logic to js/Item.html
> feat: check in/out hints

- js/Display.html
- js/app/DoCommand.html
- js/app/Modal.html
- js/app/pages/Form.html
* location select did not allow multiple changes to custom before
* time handler was written verbosely, simplified code
> fix: location select bug, time handler formatting

- css/Style.html
- gs/Main.js
- html/Form.html
- js/Utility.html
- js/app/Handlers.html
- js/app/Modal.html
- js/app/Omnibox.html
- js/app/pages/Form.html
- js/app/pages/OpenForms.html
* if omnibox cannot parse something, it will attempt to generate a list of possible matches from the inventory and roster
> feat: search button

- html/Archive.html
- html/Form.html
- js/app/main.html
- js/app/pages/ArchiveQuery.html
in on time & add practice rooms to list of locations
fixes issues 154 & 155
> feat: Only mark checkins as late if >10 minutes and no student checked

- js/app/pages/ArchiveQuery.html
fixes no show filter not working in archive view. Checks whether the
value is null and returns true if all students had null checkins.
fixes issue 157
> Fixes No-Show Filter

- .gitignore
- html/Loading.html
- html/index.html
- js/Display.html
- js/Init.html
- js/Stack.html
- js/app/Refresh.html
- js/app/Spinner.html
- js/app/main.html
- js/app/pages/Loading.html
* users land on a loading page instead of just a spinner
* the loading page shows each chunk of data as it is downloaded
* the loading page reappears each time "Open Forms" is clicked
fixes issue #161
> feat: loading page
